# Generated by Django 2.2.20 on 2021-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcc', '0008_event_is_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
