# Generated by Django 2.2.10 on 2020-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('gcc', '0009_edition_long_description')]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='long_description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='long_description_fr',
            field=models.TextField(default='', null=True),
        ),
    ]
